version: '3'
services:
 
  gvm:
    image: falkowich/gvm-docker:dev
    ports: 
      - 443:443
      - 9391:9391
        #    restart: never
    volumes:
      - psql:/var/lib/postgresql/
      - logs:/opt/gvm/var/log/gvm/
volumes:
  psql:
  logs:
