version: '3'
services:
 
  gvm:
    image: falkowich/gvm:dev
    ports: 
      - 443:443
      - 9391:9391
    restart: always
    volumes:
      - gvm:/usr/local/var/lib/gvm/
      - psql:/var/lib/postgresql/
volumes:
  gvm:
  psql: